version: "3"
services:
  mynginx:
    build:
      context: .
      dockerfile: ./docker/frontend-nginx/Dockerfile
    volumes:
      - ./docker/frontend-nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
    depends_on:
      - backend
  backend:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
